apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-application
  labels:
    app: python-application
  namespace: app
spec:
  selector:
    matchLabels:
      app: python-application
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: python-application
    spec:
      containers:
      - name: python-application
        image: docker.io/eatherv/python-application:0.0.5 #{"$imagepolicy": "flux-system:python"}
        ports:
        - containerPort: 5000
