apiVersion: v1
kind: Service
metadata:
  namespace: app
  name: python-application
  labels:
    app: python-application
spec:
  type: ClusterIP
  selector:
    app: python-application
  ports:
    - protocol: TCP
      name: http
      port: 80
      targetPort: 5000
